# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xLTojV8uoAU_UlB4AEPyNL2vO3r2MqvW
"""

import random

while True:
    roll = input("Roll the Dice?\n")
    if roll == "yes" or roll ==  "y":
        print("Rolling the Dice...")
        print("The Values are :")
        print(random.randint(1,6))
    else: 
        break